# Generated by Django 5.2.8 on 2025-12-01 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daire_no', models.CharField(max_length=5, unique=True)),
                ('metrekare', models.IntegerField(default=0)),
                ('kiraci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiraci_oldugu_daireler', to=settings.AUTH_USER_MODEL)),
                ('sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sahip_oldugu_daireler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sakin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('rol', models.CharField(choices=[('Y', 'Yönetici'), ('S', 'Sakin')], default='S', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aciklama', models.CharField(default='Aylık Aidat', max_length=200)),
                ('vade_tarihi', models.DateField()),
                ('odendi_mi', models.BooleanField(default=False)),
                ('odeme_tarihi', models.DateField(blank=True, null=True)),
                ('daire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonetim.daire')),
            ],
            options={
                'unique_together': {('daire', 'aciklama', 'vade_tarihi')},
            },
        ),
    ]
